apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 24224
      protocol: TCP
      name: "forward-port"
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
